version: "3.8"
services:
    redis:
      container_name: redis-bot
      image: redis:latest
      restart: always
      env_file:
        - .env
      ports:
        - ${REDIS_PORT}:${REDIS_PORT}
      expose:
        - ${REDIS_PORT}
